import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  "https://vbcmeueohlmutmwsknna.supabase.co",
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZiY21ldWVvaGxtdXRtd3Nrbm5hIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3Mjc5MjMzNSwiZXhwIjoyMDg4MzY4MzM1fQ.ydtUGs1mIvASa-YzE2-2A7M3EOScw6Htplil3uxW5oY"
);

const products = [
  // IKEA (15)
  { name: "KIVIK sofa", brand: "IKEA", category: "sofa", price: 5995, image_url: "https://www.ikea.com/no/no/images/products/kivik-3-seters-sofa-tresund-lys-beige__1124111_pe875024_s5.jpg", affiliate_url: "#", style_tags: ["skandinavisk","moderne"], color_tags: ["grå","beige"], room_tags: ["stue"], dimensions: {width:228,depth:95,height:83} },
  { name: "LACK salongbord", brand: "IKEA", category: "bord", price: 299, image_url: "https://www.ikea.com/no/no/images/products/lack-bord-hvit__0750652_pe746803_s5.jpg", affiliate_url: "#", style_tags: ["minimalistisk","moderne"], color_tags: ["hvit","svart"], room_tags: ["stue"], dimensions: {width:90,depth:55,height:45} },
  { name: "BILLY bokhylle", brand: "IKEA", category: "hylle", price: 699, image_url: "https://www.ikea.com/no/no/images/products/billy-bokhylle-hvit__0625599_pe692385_s5.jpg", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["hvit","tre"], room_tags: ["stue","kontor"], dimensions: {width:80,depth:28,height:202} },
  { name: "KALLAX reolenhet", brand: "IKEA", category: "hylle", price: 999, image_url: "https://www.ikea.com/no/no/images/products/kallax-hylle-hvit__0644757_pe702939_s5.jpg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["hvit","tre"], room_tags: ["stue","kontor"], dimensions: {width:77,depth:39,height:147} },
  { name: "HEMNES sengeramme", brand: "IKEA", category: "seng", price: 2495, image_url: "https://www.ikea.com/no/no/images/products/hemnes-seng-hvit-beis__0637516_pe698353_s5.jpg", affiliate_url: "#", style_tags: ["tradisjonell"], color_tags: ["hvit","tre"], room_tags: ["soverom"], dimensions: {width:174,depth:211,height:66} },
  { name: "POÄNG lenestol", brand: "IKEA", category: "stol", price: 1495, image_url: "https://www.ikea.com/no/no/images/products/poaeng-lenestol-bjorkefiner-hillared-antrasitt__0497120_pe628947_s5.jpg", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["tre","beige"], room_tags: ["stue"], dimensions: {width:68,depth:82,height:100} },
  { name: "STOCKHOLM teppe", brand: "IKEA", category: "teppe", price: 2495, image_url: "https://www.ikea.com/no/no/images/products/stockholm-teppe-flatvevd-handlaget-stripet-svart-offwhite__56123_pe161531_s5.jpg", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["grå","hvit"], room_tags: ["stue"], dimensions: {width:170,depth:240,height:1} },
  { name: "HEKTAR gulvlampe", brand: "IKEA", category: "lampe", price: 499, image_url: "https://www.ikea.com/no/no/images/products/hektar-gulvlampe-mork-gra__0149974_pe308131_s5.jpg", affiliate_url: "#", style_tags: ["industriell"], color_tags: ["svart"], room_tags: ["stue","soverom"], dimensions: {width:32,depth:32,height:181} },
  { name: "BESTÅ TV-benk", brand: "IKEA", category: "hylle", price: 1795, image_url: "https://www.ikea.com/no/no/images/products/besta-tv-benk-hvit__0384984_pe557581_s5.jpg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["hvit","tre"], room_tags: ["stue"], dimensions: {width:180,depth:40,height:38} },
  { name: "MALM kommode", brand: "IKEA", category: "kommode", price: 1695, image_url: "https://www.ikea.com/no/no/images/products/malm-kommode-med-3-skuffer-hvit__0484875_pe621342_s5.jpg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["hvit","tre"], room_tags: ["soverom"], dimensions: {width:80,depth:48,height:100} },
  { name: "EKTORP sofa 3-seter", brand: "IKEA", category: "sofa", price: 7995, image_url: "https://www.ikea.com/no/no/images/products/ektorp-3-seters-sofa-tallmyra-beige__0779512_pe759553_s5.jpg", affiliate_url: "#", style_tags: ["tradisjonell"], color_tags: ["hvit","beige"], room_tags: ["stue"], dimensions: {width:218,depth:88,height:88} },
  { name: "STOCKHOLM 2017 teppe", brand: "IKEA", category: "teppe", price: 3495, image_url: "https://www.ikea.com/no/no/images/products/stockholm-teppe-flatvevd-handlaget-stripet-svart-offwhite__56123_pe161531_s5.jpg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["grå"], room_tags: ["stue"], dimensions: {width:200,depth:300,height:1} },
  { name: "SYMFONISK wifi-høyttaler", brand: "IKEA", category: "dekor", price: 1299, image_url: "https://www.ikea.com/no/no/images/products/symfonisk-lampefot-med-tradlos-hoyttaler-hvit-smart__0993364_pe820510_s5.jpg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["hvit","svart"], room_tags: ["stue"], dimensions: {width:15,depth:10,height:31} },
  { name: "FEJKA kunstig plante", brand: "IKEA", category: "dekor", price: 149, image_url: "https://www.ikea.com/no/no/images/products/fejka-kunstig-potteplante-inne-ute-eukalyptus__0674947_pe718059_s5.jpg", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["grønn"], room_tags: ["stue"], dimensions: {width:12,depth:12,height:28} },

  // Bohus (5)

  // Bolia (5)
  { name: "Scandinavia sofa", brand: "Bolia", category: "sofa", price: 19995, image_url: "https://images.bolia.com/cdn-cgi/image/width=1100,height=530,fit=pad/products/01-026-20_8112329.webp?cachebusting=2", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["beige","grå"], room_tags: ["stue"], dimensions: {width:250,depth:96,height:80} },
  { name: "Como sofabord", brand: "Bolia", category: "bord", price: 4995, image_url: "https://images.bolia.com/cdn-cgi/image/width=1100,height=530,fit=pad/products/03-033-70_6816336.webp?cachebusting=2", affiliate_url: "#", style_tags: ["minimalistisk"], color_tags: ["hvit","tre"], room_tags: ["stue"], dimensions: {width:120,depth:60,height:40} },
  { name: "Nomad stol", brand: "Bolia", category: "stol", price: 3495, image_url: "https://images.bolia.com/cdn-cgi/image/width=1100,height=530,fit=pad/products/02-103-10_00002.webp?cachebusting=0", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["svart","tre"], room_tags: ["stue","kontor"], dimensions: {width:55,depth:56,height:80} },
  { name: "Alba sidebord", brand: "Bolia", category: "bord", price: 2995, image_url: "https://images.bolia.com/cdn-cgi/image/width=1100,height=530,fit=pad/products/03-105-15_00003.webp?cachebusting=2", affiliate_url: "#", style_tags: ["minimalistisk"], color_tags: ["hvit","tre"], room_tags: ["stue"], dimensions: {width:45,depth:45,height:50} },
  { name: "Stay lampe", brand: "Bolia", category: "lampe", price: 3995, image_url: "https://images.bolia.com/cdn-cgi/image/width=1100,height=530,fit=pad/products/20-129-01_00001.webp?cachebusting=2", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["hvit","messing"], room_tags: ["stue"], dimensions: {width:30,depth:30,height:145} },

  // Jysk (5)
  { name: "AARUP sofa", brand: "Jysk", category: "sofa", price: 3999, image_url: "https://s3.eu-west-2.amazonaws.com/imagerepositorypressloft/clients/36565/m/7879452_m.jpg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["grå"], room_tags: ["stue"], dimensions: {width:200,depth:85,height:78} },
  { name: "BANDHOLM seng", brand: "Jysk", category: "seng", price: 1999, image_url: "https://s3.eu-west-2.amazonaws.com/imagerepositorypressloft/clients/36565/m/7260585_m.jpg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["hvit","tre"], room_tags: ["soverom"], dimensions: {width:160,depth:200,height:45} },
  { name: "VALLBY pute", brand: "Jysk", category: "pute", price: 149, image_url: "https://s3.eu-west-2.amazonaws.com/imagerepositorypressloft/clients/36565/m/7266172_m.jpg", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["beige","brun"], room_tags: ["stue","soverom"], dimensions: {width:45,depth:45,height:10} },
  { name: "JONSTRUP hylle", brand: "Jysk", category: "hylle", price: 399, image_url: "https://s3.eu-west-2.amazonaws.com/imagerepositorypressloft/clients/36565/m/7316644_m.jpg", affiliate_url: "#", style_tags: ["industriell"], color_tags: ["svart","tre"], room_tags: ["stue"], dimensions: {width:60,depth:24,height:85} },

  // Kid (5)
  { name: "Arild pute", brand: "Kid", category: "pute", price: 299, image_url: "https://www.kid.no/globalassets/productimages/206562060200_.jpg?ref=8B529452BA&w=590&h=787&mode=pad", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["hvit","rosa"], room_tags: ["stue","soverom"], dimensions: {width:50,depth:50,height:12} },
  { name: "Sandnes pledd", brand: "Kid", category: "dekor", price: 699, image_url: "https://www.kid.no/globalassets/productimages/213076145000.jpg?ref=F29982B86B&w=590&h=787&mode=pad", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["grå"], room_tags: ["stue","soverom"], dimensions: {width:130,depth:170,height:1} },
  { name: "Frogner pute 2-pk", brand: "Kid", category: "pute", price: 249, image_url: "https://www.kid.no/globalassets/productimages/200099050157.jpg?ref=B242440397&w=590&h=787&mode=pad", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["blå","hvit"], room_tags: ["stue"], dimensions: {width:45,depth:45,height:12} },
  { name: "Stavern dekorpute", brand: "Kid", category: "pute", price: 399, image_url: "https://www.kid.no/globalassets/productimages/208611060818.jpg?ref=8124520631&w=590&h=787&mode=pad", affiliate_url: "#", style_tags: ["boho"], color_tags: ["terrakotta"], room_tags: ["stue"], dimensions: {width:50,depth:50,height:14} },
  { name: "Arendal teppe", brand: "Kid", category: "teppe", price: 1499, image_url: "https://www.kid.no/globalassets/productimages/213374150070.jpg?ref=4B77D2AFEE&w=590&h=787&mode=pad", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["hvit","grå"], room_tags: ["stue"], dimensions: {width:160,depth:230,height:1} },

  // Skeidar (5)
  { name: "Harmony sofa", brand: "Skeidar", category: "sofa", price: 14990, image_url: "https://www.skeidar.no/globalassets/9999/alle-produkter/alle-sofaer/sofa/112295_sjv2oehneve16sorteben_100_001.jpg?id=q9oWq+", affiliate_url: "#", style_tags: ["moderne","skandinavisk"], color_tags: ["grå","beige"], room_tags: ["stue"], dimensions: {width:245,depth:96,height:82} },
  { name: "Nordic spisebord", brand: "Skeidar", category: "bord", price: 6990, image_url: "https://www.skeidar.no/globalassets/9999/alle-produkter/alle-bord/spisebord/108880_210cm_hvitoljet_100_001.jpg?id=6e+C9n", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["tre"], room_tags: ["kjøkken","stue"], dimensions: {width:180,depth:90,height:75} },
  { name: "Oslo nattbord", brand: "Skeidar", category: "bord", price: 1990, image_url: "https://www.skeidar.no/globalassets/9999/alle-produkter/alle-bord/sofabord/112377_80x80cm_beige_sortstal_100_001.jpg?id=QLiz9Q", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["hvit","tre"], room_tags: ["soverom"], dimensions: {width:45,depth:38,height:55} },
  { name: "Bergen bokhylle", brand: "Skeidar", category: "hylle", price: 4490, image_url: "https://www.skeidar.no/globalassets/9999/alle-produkter/all-oppbevaring-og-skap/hyller-og-reoler/115398_100_001.jpg?id=x8sVZw", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["tre","hvit"], room_tags: ["stue","kontor"], dimensions: {width:90,depth:30,height:190} },
  { name: "Aurora gulvlampe", brand: "Skeidar", category: "lampe", price: 2990, image_url: "https://www.skeidar.no/globalassets/9999/alle-produkter/all-belysning/bordlamper/113570_100_001.jpg?id=ItFWhU", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["svart","messing"], room_tags: ["stue"], dimensions: {width:38,depth:38,height:165} },

  // Norsk Interiør (5)

  // ── Expansion: IKEA (10) ─────────────────────────────────
  { name: "LISABO spisebord", brand: "IKEA", category: "bord", price: 1495, image_url: "https://www.ikea.com/no/no/images/products/lisabo-bord-askefiner__0737105_pe740883_s5.jpg", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["tre"], room_tags: ["kjøkken","stue"], dimensions: {width:140,depth:78,height:74} },
  { name: "STRANDMON lenestol", brand: "IKEA", category: "stol", price: 2995, image_url: "https://www.ikea.com/no/no/images/products/strandmon-orelappstol-nordvalla-mork-gra__0325432_pe517964_s5.jpg", affiliate_url: "#", style_tags: ["tradisjonell"], color_tags: ["grå","blå"], room_tags: ["stue"], dimensions: {width:82,depth:96,height:101} },
  { name: "RANARP bordlampe", brand: "IKEA", category: "lampe", price: 349, image_url: "https://www.ikea.com/no/no/images/products/ranarp-gulv-leselampe-svart__0606896_pe682604_s5.jpg", affiliate_url: "#", style_tags: ["industriell"], color_tags: ["svart"], room_tags: ["kontor","soverom"], dimensions: {width:19,depth:19,height:42} },
  { name: "NORDLI kommode", brand: "IKEA", category: "kommode", price: 2295, image_url: "https://www.ikea.com/no/no/images/products/nordli-kommode-6-skuffer-hvit__0555314_pe660399_s5.jpg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["hvit"], room_tags: ["soverom"], dimensions: {width:120,depth:47,height:99} },
  { name: "IDANÄS seng", brand: "IKEA", category: "seng", price: 3495, image_url: "https://www.ikea.com/no/no/images/products/idanaes-seng-med-skuffer-hvit-loenset__1151017_pe884724_s5.jpg", affiliate_url: "#", style_tags: ["tradisjonell"], color_tags: ["hvit"], room_tags: ["soverom"], dimensions: {width:167,depth:216,height:98} },

  // ── Expansion: Bohus (7) ─────────────────────────────────

  // ── Expansion: Bolia (8) ─────────────────────────────────
  { name: "Luca sofa", brand: "Bolia", category: "sofa", price: 24995, image_url: "https://images.bolia.com/cdn-cgi/image/width=1100,height=530,fit=pad/products/01-026-20_8112329.webp?cachebusting=2", affiliate_url: "#", style_tags: ["moderne","minimalistisk"], color_tags: ["grå"], room_tags: ["stue"], dimensions: {width:230,depth:95,height:75} },
  { name: "Floema spisebord", brand: "Bolia", category: "bord", price: 12995, image_url: "https://images.bolia.com/cdn-cgi/image/width=1100,height=530,fit=pad/products/03-114-30_00002.webp?cachebusting=3", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["tre"], room_tags: ["kjøkken","stue"], dimensions: {width:200,depth:95,height:73} },
  { name: "Mara lenestol", brand: "Bolia", category: "stol", price: 6995, image_url: "https://images.bolia.com/cdn-cgi/image/width=1100,height=530,fit=pad/products/02-103-10_00002.webp?cachebusting=0", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["grønn","tre"], room_tags: ["stue"], dimensions: {width:70,depth:75,height:78} },
  { name: "Orb taklampe", brand: "Bolia", category: "lampe", price: 2995, image_url: "https://images.bolia.com/cdn-cgi/image/width=1100,height=530,fit=pad/products/20-116-03_8305164.webp?cachebusting=2", affiliate_url: "#", style_tags: ["minimalistisk"], color_tags: ["hvit"], room_tags: ["stue","kjøkken"], dimensions: {width:40,depth:40,height:25} },
  { name: "Pebble teppe", brand: "Bolia", category: "teppe", price: 5995, image_url: "https://images.bolia.com/cdn-cgi/image/width=1100,height=530,fit=pad/products/22-152-22_00001.webp?cachebusting=2", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["beige","hvit"], room_tags: ["stue"], dimensions: {width:200,depth:300,height:2} },
  { name: "Cloud pute", brand: "Bolia", category: "pute", price: 799, image_url: "https://images.bolia.com/cdn-cgi/image/width=1100,height=530,fit=pad/products/21-006-03_10716038.webp?cachebusting=0", affiliate_url: "#", style_tags: ["minimalistisk"], color_tags: ["hvit","grå"], room_tags: ["stue","soverom"], dimensions: {width:50,depth:50,height:15} },
  { name: "Saga hylle", brand: "Bolia", category: "hylle", price: 7995, image_url: "https://images.bolia.com/cdn-cgi/image/width=1100,height=530,fit=pad/products/04-150-01_00004.webp?cachebusting=2", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["tre"], room_tags: ["stue","kontor"], dimensions: {width:120,depth:35,height:180} },
  { name: "Loft seng", brand: "Bolia", category: "seng", price: 14995, image_url: "https://images.bolia.com/cdn-cgi/image/width=1100,height=530,fit=pad/products/01-500-10_00002.webp?cachebusting=4", affiliate_url: "#", style_tags: ["skandinavisk","moderne"], color_tags: ["tre","grå"], room_tags: ["soverom"], dimensions: {width:180,depth:215,height:40} },

  // ── Expansion: Jysk (7) ──────────────────────────────────
  { name: "AULUM sofa", brand: "Jysk", category: "sofa", price: 4499, image_url: "https://s3.eu-west-2.amazonaws.com/imagerepositorypressloft/clients/36565/m/7260632_m.jpg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["blå"], room_tags: ["stue"], dimensions: {width:220,depth:88,height:80} },
  { name: "TERSLEV spisebord", brand: "Jysk", category: "bord", price: 2499, image_url: "https://s3.eu-west-2.amazonaws.com/imagerepositorypressloft/clients/36565/m/8616897_m.jpg", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["tre"], room_tags: ["kjøkken","stue"], dimensions: {width:150,depth:80,height:75} },
  { name: "JELLING stol", brand: "Jysk", category: "stol", price: 799, image_url: "https://s3.eu-west-2.amazonaws.com/imagerepositorypressloft/clients/36565/m/7316651_m.jpg", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["tre","grå"], room_tags: ["kjøkken","stue"], dimensions: {width:48,depth:52,height:80} },
  { name: "BROBY lampe", brand: "Jysk", category: "lampe", price: 399, image_url: "https://s3.eu-west-2.amazonaws.com/imagerepositorypressloft/clients/36565/m/7930989_m.jpg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["svart"], room_tags: ["stue","soverom"], dimensions: {width:25,depth:25,height:150} },
  { name: "RAVNSBORG kommode", brand: "Jysk", category: "kommode", price: 1499, image_url: "https://s3.eu-west-2.amazonaws.com/imagerepositorypressloft/clients/36565/m/7260601_m.jpg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["hvit","tre"], room_tags: ["soverom"], dimensions: {width:80,depth:40,height:95} },
  { name: "VEDERSØ dekorpute", brand: "Jysk", category: "pute", price: 199, image_url: "https://s3.eu-west-2.amazonaws.com/imagerepositorypressloft/clients/36565/m/8367858_m.jpg", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["grå","hvit"], room_tags: ["stue"], dimensions: {width:45,depth:45,height:12} },
  { name: "HORNSLET dekorvase", brand: "Jysk", category: "dekor", price: 249, image_url: "https://s3.eu-west-2.amazonaws.com/imagerepositorypressloft/clients/36565/m/8367826_m.jpg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["svart"], room_tags: ["stue"], dimensions: {width:12,depth:12,height:25} },

  // ── Expansion: Kid (8) ───────────────────────────────────
  { name: "Tromsø lampe", brand: "Kid", category: "lampe", price: 599, image_url: "https://www.kid.no/globalassets/productimages/210958032210.jpg?ref=385BD28407&w=590&h=787&mode=pad", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["hvit","tre"], room_tags: ["stue","soverom"], dimensions: {width:30,depth:30,height:45} },
  { name: "Hamar pledd", brand: "Kid", category: "dekor", price: 499, image_url: "https://www.kid.no/globalassets/productimages/205018021920.jpg?ref=EC43F9FEB2&w=590&h=787&mode=pad", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["beige","hvit"], room_tags: ["stue","soverom"], dimensions: {width:130,depth:170,height:1} },
  { name: "Bergen pute", brand: "Kid", category: "pute", price: 349, image_url: "https://www.kid.no/globalassets/productimages/115206036.jpg?ref=0F1AC3E1E8&w=590&h=787&mode=pad", affiliate_url: "#", style_tags: ["boho"], color_tags: ["grønn"], room_tags: ["stue"], dimensions: {width:50,depth:50,height:15} },
  { name: "Lillehammer hylle", brand: "Kid", category: "hylle", price: 899, image_url: "https://www.kid.no/globalassets/productimages/206059035900_5.jpg?ref=DA31B7F98C&w=590&h=787&mode=pad", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["hvit"], room_tags: ["stue","soverom"], dimensions: {width:60,depth:20,height:80} },

  // ── Expansion: Skeidar (7) ───────────────────────────────
  { name: "Fjell sofa", brand: "Skeidar", category: "sofa", price: 11990, image_url: "https://www.skeidar.no/globalassets/9999/alle-produkter/alle-sofaer/sofa/112295_sjv2oehneve16sorteben_100_001.jpg?id=q9oWq+", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["blå","grå"], room_tags: ["stue"], dimensions: {width:235,depth:92,height:80} },
  { name: "Voss lenestol", brand: "Skeidar", category: "stol", price: 4990, image_url: "https://www.skeidar.no/globalassets/9999/alle-produkter/alle-stoler/lenestoler/113683_slowlygra_100_001.jpg?id=xW3aXc", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["grønn","tre"], room_tags: ["stue"], dimensions: {width:75,depth:80,height:90} },
  { name: "Gol teppe", brand: "Skeidar", category: "teppe", price: 2990, image_url: "https://www.skeidar.no/globalassets/9999/alle-produkter/alle-tepper/gulvtepper/103422_160x230cm_hvit_000_001.jpg?id=efinbX", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["beige","hvit"], room_tags: ["stue"], dimensions: {width:200,depth:290,height:1} },
  { name: "Rena pute", brand: "Skeidar", category: "pute", price: 399, image_url: "https://www.skeidar.no/globalassets/9999/alle-produkter/alle-tekstiler-og-sengetoy/pynteputer-og-putetrekk/117938_100_001.jpg?id=JDPSIY", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["blå","hvit"], room_tags: ["stue","soverom"], dimensions: {width:50,depth:50,height:15} },
  { name: "Hamar kommode", brand: "Skeidar", category: "kommode", price: 5990, image_url: "https://www.skeidar.no/globalassets/9999/alle-produkter/all-oppbevaring-og-skap/kommoder/111878_3_sort_000_001.jpg?id=6I6N7q", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["hvit","tre"], room_tags: ["soverom"], dimensions: {width:120,depth:45,height:80} },
  { name: "Elverum seng", brand: "Skeidar", category: "seng", price: 8990, image_url: "https://www.skeidar.no/globalassets/9999/alle-produkter/alle-senger-og-madrasser/kontinentalsenger/116246_180x200cmtesktilcloud08beigefastfast_000_001.jpg?id=JMt171", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["tre"], room_tags: ["soverom"], dimensions: {width:180,depth:215,height:95} },
  { name: "Lillestrøm dekorlys", brand: "Skeidar", category: "dekor", price: 299, image_url: "https://www.skeidar.no/globalassets/9999/alle-produkter/alle-dekorartikler/dekor-og-pynt/113423_100_001.jpg?id=KIKkFp", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["hvit"], room_tags: ["stue","soverom"], dimensions: {width:10,depth:10,height:20} },

  // ── Expansion: Norsk Interiør (7) ────────────────────────

    // -- Nye butikker (119) --
    // Princess (14)
    { name: "Silke putetrekk grå", brand: "Princess", category: "dekor", price: 179, image_url: "https://princessbutikken.b-cdn.net/images/thumbs/0025962_kikki-pyntepute-o40-lys-gronn_550.jpeg", affiliate_url: "#", style_tags: ["luksus"], color_tags: ["grå"], room_tags: ["soverom"], dimensions: {width:50,depth:50,height:1}, in_stock: true },
    { name: "Flanell sengetøy hvit", brand: "Princess", category: "dekor", price: 399, image_url: "https://princessbutikken.b-cdn.net/images/thumbs/0033218_hailey-pledd-130x170-beige_550.jpeg", affiliate_url: "#", style_tags: ["komfortabel"], color_tags: ["hvit"], room_tags: ["soverom"], dimensions: {width:200,depth:0,height:0}, in_stock: true },
    { name: "Mykt pledd taupe", brand: "Princess", category: "dekor", price: 449, image_url: "https://princessbutikken.b-cdn.net/images/thumbs/0039411_andrina-lysestake-19-cm_550.jpeg", affiliate_url: "#", style_tags: ["komfortabel"], color_tags: ["taupe"], room_tags: ["stue", "soverom"], dimensions: {width:150,depth:200,height:1}, in_stock: true },
    { name: "Frotté håndkle sett", brand: "Princess", category: "dekor", price: 149, image_url: "https://princessbutikken.b-cdn.net/images/thumbs/0025962_kikki-pyntepute-o40-lys-gronn_550.jpeg", affiliate_url: "#", style_tags: ["praktisk"], color_tags: ["hvit", "grå"], room_tags: ["bad"], dimensions: {width:50,depth:80,height:1}, in_stock: true },
    // Møbelringen (15)
    { name: "Milano hjørnesofa grå", brand: "Møbelringen", category: "sofa", price: 12990, image_url: "https://backend.mobelringen.no/media/catalog/product/3/2/322319001_8639326.png?width=650&height=650&quality=80&fit=bounds&optimise=high", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["grå"], room_tags: ["stue"], dimensions: {width:280,depth:100,height:85}, in_stock: true },
    { name: "Oslo sengeramme hvit", brand: "Møbelringen", category: "seng", price: 4490, image_url: "https://backend.mobelringen.no/media/catalog/product/6/1/6122171_lyngen_kontinental_line_r_oda_creme_ps_ka_dir398908004_398908006_398908001_398908003_3.png?width=650&height=650&quality=80&fit=bounds&optimise=high", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["hvit"], room_tags: ["soverom"], dimensions: {width:160,depth:210,height:95}, in_stock: true },
    { name: "Bergen spisebord eik", brand: "Møbelringen", category: "bord", price: 5990, image_url: "https://backend.mobelringen.no/media/catalog/product/3/1/319190_8804492.png?width=650&height=650&quality=80&fit=bounds&optimise=high", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["tre"], room_tags: ["kjøkken", "stue"], dimensions: {width:180,depth:90,height:75}, in_stock: true },
    { name: "Stockholm stol grå", brand: "Møbelringen", category: "stol", price: 1890, image_url: "https://backend.mobelringen.no/media/catalog/product/3/7/373073_9061429.png?width=650&height=650&quality=80&fit=bounds&optimise=high", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["grå"], room_tags: ["stue", "kontor"], dimensions: {width:58,depth:56,height:88}, in_stock: true },
    { name: "Roma 3-seter sofa beige", brand: "Møbelringen", category: "sofa", price: 8990, image_url: "https://backend.mobelringen.no/media/catalog/product/3/2/322319001_8639326.png?width=650&height=650&quality=80&fit=bounds&optimise=high", affiliate_url: "#", style_tags: ["klassisk"], color_tags: ["beige"], room_tags: ["stue"], dimensions: {width:220,depth:95,height:88}, in_stock: true },
    { name: "Kristiansand kommode", brand: "Møbelringen", category: "kommode", price: 3490, image_url: "https://backend.mobelringen.no/media/catalog/product/5/7/5755383_oslo_kommode_4_skf_copy.png?width=650&height=650&quality=80&fit=bounds&optimise=high", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["hvit", "tre"], room_tags: ["soverom"], dimensions: {width:80,depth:45,height:95}, in_stock: true },
    { name: "Tromsø hylle hvit", brand: "Møbelringen", category: "hylle", price: 2290, image_url: "https://backend.mobelringen.no/media/catalog/product/3/2/326024_8716944.png?width=650&height=650&quality=80&fit=bounds&optimise=high", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["hvit"], room_tags: ["stue", "kontor"], dimensions: {width:90,depth:30,height:180}, in_stock: true },
    { name: "Stavanger TV-benk grå", brand: "Møbelringen", category: "hylle", price: 2890, image_url: "https://backend.mobelringen.no/media/catalog/product/2/4/243912_9045289.png?width=650&height=650&quality=80&fit=bounds&optimise=high", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["grå"], room_tags: ["stue"], dimensions: {width:150,depth:42,height:55}, in_stock: true },
    { name: "Ålesund spisestol svart", brand: "Møbelringen", category: "stol", price: 699, image_url: "https://backend.mobelringen.no/media/catalog/product/3/7/373073_9061429.png?width=650&height=650&quality=80&fit=bounds&optimise=high", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["svart"], room_tags: ["kjøkken"], dimensions: {width:48,depth:52,height:90}, in_stock: true },
    { name: "Fredrikstad sofabord eik", brand: "Møbelringen", category: "bord", price: 1990, image_url: "https://backend.mobelringen.no/media/catalog/product/5/7/5743613_como_sofabord_90_cm_hvitoljet_ps_ka_copy_dir.png?width=650&height=650&quality=80&fit=bounds&optimise=high", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["tre"], room_tags: ["stue"], dimensions: {width:110,depth:65,height:45}, in_stock: true },
    { name: "Lillehammer divan grå", brand: "Møbelringen", category: "seng", price: 3990, image_url: "https://backend.mobelringen.no/media/catalog/product/6/1/6122171_lyngen_kontinental_line_r_oda_creme_ps_ka_dir398908004_398908006_398908001_398908003_3.png?width=650&height=650&quality=80&fit=bounds&optimise=high", affiliate_url: "#", style_tags: ["komfortabel"], color_tags: ["grå"], room_tags: ["soverom"], dimensions: {width:160,depth:210,height:85}, in_stock: true },
    { name: "Trondheim nattbord hvit", brand: "Møbelringen", category: "bord", price: 899, image_url: "https://backend.mobelringen.no/media/catalog/product/3/1/319190_8804492.png?width=650&height=650&quality=80&fit=bounds&optimise=high", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["hvit"], room_tags: ["soverom"], dimensions: {width:45,depth:38,height:55}, in_stock: true },
    { name: "Sandnes fåtølj grå", brand: "Møbelringen", category: "stol", price: 2990, image_url: "https://backend.mobelringen.no/media/catalog/product/3/7/373073_9061429.png?width=650&height=650&quality=80&fit=bounds&optimise=high", affiliate_url: "#", style_tags: ["klassisk"], color_tags: ["grå"], room_tags: ["stue"], dimensions: {width:72,depth:80,height:95}, in_stock: true },
    { name: "Hammerfest seng eik", brand: "Møbelringen", category: "seng", price: 5490, image_url: "https://backend.mobelringen.no/media/catalog/product/6/1/6122171_lyngen_kontinental_line_r_oda_creme_ps_ka_dir398908004_398908006_398908001_398908003_3.png?width=650&height=650&quality=80&fit=bounds&optimise=high", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["tre"], room_tags: ["soverom"], dimensions: {width:180,depth:210,height:100}, in_stock: true },
    { name: "Bodø stol med armlener", brand: "Møbelringen", category: "stol", price: 1590, image_url: "https://backend.mobelringen.no/media/catalog/product/3/7/373073_9061429.png?width=650&height=650&quality=80&fit=bounds&optimise=high", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["beige"], room_tags: ["stue"], dimensions: {width:65,depth:68,height:92}, in_stock: true },
    // Fagmøbler (15)
    { name: "Spisebord 200cm", brand: "Fagmøbler", category: "bord", price: 7990, image_url: "https://imagedelivery.net/LfHarEEHw85fo7v7-lUDxQ/c2d18264-7469-4022-1d94-4fd286336d00/public", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["tre"], room_tags: ["kjøkken"], dimensions: {width:200,depth:95,height:75}, in_stock: true },
    { name: "Spisebord 180cm eik", brand: "Fagmøbler", category: "bord", price: 6490, image_url: "https://imagedelivery.net/LfHarEEHw85fo7v7-lUDxQ/c2d18264-7469-4022-1d94-4fd286336d00/public", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["tre"], room_tags: ["kjøkken"], dimensions: {width:180,depth:90,height:75}, in_stock: true },
    { name: "Spisebord 160cm", brand: "Fagmøbler", category: "bord", price: 4990, image_url: "https://imagedelivery.net/LfHarEEHw85fo7v7-lUDxQ/c2d18264-7469-4022-1d94-4fd286336d00/public", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["tre"], room_tags: ["kjøkken"], dimensions: {width:160,depth:85,height:75}, in_stock: true },
    { name: "Spisebord med ileggsplater", brand: "Fagmøbler", category: "bord", price: 8990, image_url: "https://imagedelivery.net/LfHarEEHw85fo7v7-lUDxQ/c2d18264-7469-4022-1d94-4fd286336d00/public", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["tre"], room_tags: ["kjøkken"], dimensions: {width:200,depth:95,height:75}, in_stock: true },
    { name: "Spisebord smalt", brand: "Fagmøbler", category: "bord", price: 5490, image_url: "https://imagedelivery.net/LfHarEEHw85fo7v7-lUDxQ/c2d18264-7469-4022-1d94-4fd286336d00/public", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["tre"], room_tags: ["kjøkken"], dimensions: {width:140,depth:80,height:75}, in_stock: true },
    // Home & Cottage (13)
    // Elkjøp (12)
    { name: "LED Dekor Spiral 3,5W", brand: "Elkjøp", category: "lampe", price: 118, image_url: "https://next-media.elkjop.com/image/dv_web_D180001005124200/60589/krystall-lampe-magisk-glasskule.jpg?w=640&q=75", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["gull"], room_tags: ["stue"], dimensions: {width:10,depth:10,height:12}, in_stock: true },
    { name: "Smart LED lampe LIFX", brand: "Elkjøp", category: "lampe", price: 449, image_url: "https://next-media.elkjop.com/image/dv_web_D180001280327476/283375/led-mane-lampe-18-cm.jpg?w=640&q=75", affiliate_url: "#", style_tags: ["smart"], color_tags: ["hvit"], room_tags: ["stue", "soverom"], dimensions: {width:6,depth:6,height:10}, in_stock: true },
    { name: "Philips Hue starter kit", brand: "Elkjøp", category: "lampe", price: 799, image_url: "https://next-media.elkjop.com/image/dv_web_D18000130317980/883921/moderne-bordlampe-med-beroringsfunksjon-fra-articasa-metall-svart.jpg", affiliate_url: "#", style_tags: ["smart"], color_tags: ["hvit"], room_tags: ["stue"], dimensions: {width:15,depth:15,height:12}, in_stock: true },
    { name: "RGB LED Strip lys 20M", brand: "Elkjøp", category: "lampe", price: 399, image_url: "https://next-media.elkjop.com/image/dv_web_D180001005124200/60589/krystall-lampe-magisk-glasskule.jpg?w=640&q=75", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["flerfarga"], room_tags: ["stue"], dimensions: {width:2000,depth:1,height:1}, in_stock: true },
    { name: "LED Lysslynge batteri", brand: "Elkjøp", category: "lampe", price: 199, image_url: "https://next-media.elkjop.com/image/dv_web_D180001280327476/283375/led-mane-lampe-18-cm.jpg?w=640&q=75", affiliate_url: "#", style_tags: ["dekorativ"], color_tags: ["varm hvit"], room_tags: ["stue"], dimensions: {width:300,depth:1,height:1}, in_stock: true },
    { name: "WiZ smart lyspærer", brand: "Elkjøp", category: "lampe", price: 199, image_url: "https://next-media.elkjop.com/image/dv_web_D18000130317980/883921/moderne-bordlampe-med-beroringsfunksjon-fra-articasa-metall-svart.jpg", affiliate_url: "#", style_tags: ["smart"], color_tags: ["hvit"], room_tags: ["stue"], dimensions: {width:6,depth:6,height:11}, in_stock: true },
    { name: "Nanoleaf LED paneler", brand: "Elkjøp", category: "lampe", price: 999, image_url: "https://next-media.elkjop.com/image/dv_web_D180001005124200/60589/krystall-lampe-magisk-glasskule.jpg?w=640&q=75", affiliate_url: "#", style_tags: ["design"], color_tags: ["flerfarga"], room_tags: ["stue"], dimensions: {width:17,depth:17,height:4}, in_stock: true },
    { name: "LED skrivebord lampe", brand: "Elkjøp", category: "lampe", price: 349, image_url: "https://next-media.elkjop.com/image/dv_web_D180001280327476/283375/led-mane-lampe-18-cm.jpg?w=640&q=75", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["svart"], room_tags: ["kontor"], dimensions: {width:15,depth:15,height:35}, in_stock: true },
    { name: "LED vegglampe", brand: "Elkjøp", category: "lampe", price: 299, image_url: "https://next-media.elkjop.com/image/dv_web_D18000130317980/883921/moderne-bordlampe-med-beroringsfunksjon-fra-articasa-metall-svart.jpg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["hvit"], room_tags: ["stue", "gang"], dimensions: {width:20,depth:20,height:8}, in_stock: true },
    { name: "Gradient lysremsett", brand: "Elkjøp", category: "lampe", price: 699, image_url: "https://next-media.elkjop.com/image/dv_web_D180001005124200/60589/krystall-lampe-magisk-glasskule.jpg?w=640&q=75", affiliate_url: "#", style_tags: ["design"], color_tags: ["flerfarga"], room_tags: ["stue"], dimensions: {width:250,depth:1,height:1}, in_stock: true },
    // Kremmerhuset (12)
    { name: "Kubisk duftlys hvit", brand: "Kremmerhuset", category: "dekor", price: 79, image_url: "https://kremmerhuset.no/sites/default/files/styles/product_zoom/public/product_images/1734722899-7071100791634.jpg", affiliate_url: "#", style_tags: ["klassisk"], color_tags: ["hvit"], room_tags: ["stue"], dimensions: {width:6,depth:6,height:6}, in_stock: true },
    { name: "Kronelys sett 4stk", brand: "Kremmerhuset", category: "dekor", price: 99, image_url: "https://kremmerhuset.no/sites/default/files/styles/product_zoom/public/product_images/1734723049-7071100792525.jpg", affiliate_url: "#", style_tags: ["klassisk"], color_tags: ["hvit"], room_tags: ["stue"], dimensions: {width:2,depth:2,height:5}, in_stock: true },
    { name: "Glitterlys lysemitter", brand: "Kremmerhuset", category: "lampe", price: 149, image_url: "https://kremmerhuset.no/sites/default/files/product_images/1671557249-7071100774668.jpg", affiliate_url: "#", style_tags: ["dekorativ"], color_tags: ["gull"], room_tags: ["stue"], dimensions: {width:8,depth:8,height:10}, in_stock: true },
    { name: "Lanterne grå betong", brand: "Kremmerhuset", category: "dekor", price: 199, image_url: "https://kremmerhuset.no/sites/default/files/styles/product_zoom/public/product_images/1734722899-7071100791634.jpg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["grå"], room_tags: ["utendør"], dimensions: {width:20,depth:20,height:25}, in_stock: true },
    { name: "Innrednings tekstil grå", brand: "Kremmerhuset", category: "dekor", price: 149, image_url: "https://kremmerhuset.no/sites/default/files/styles/product_zoom/public/product_images/1734723049-7071100792525.jpg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["grå"], room_tags: ["stue"], dimensions: {width:45,depth:45,height:1}, in_stock: true },
    { name: "Servett sett farget", brand: "Kremmerhuset", category: "dekor", price: 69, image_url: "https://kremmerhuset.no/sites/default/files/styles/product_zoom/public/product_images/1734722899-7071100791634.jpg", affiliate_url: "#", style_tags: ["festlig"], color_tags: ["flerfarga"], room_tags: ["kjøkken"], dimensions: {width:33,depth:33,height:1}, in_stock: true },
    { name: "Glasslykt med henkel", brand: "Kremmerhuset", category: "dekor", price: 129, image_url: "https://kremmerhuset.no/sites/default/files/styles/product_zoom/public/product_images/1734723049-7071100792525.jpg", affiliate_url: "#", style_tags: ["klassisk"], color_tags: ["klar"], room_tags: ["utendør"], dimensions: {width:12,depth:12,height:20}, in_stock: true },
    { name: "Dekorasjonspenger gull", brand: "Kremmerhuset", category: "dekor", price: 89, image_url: "https://kremmerhuset.no/sites/default/files/styles/product_zoom/public/product_images/1734722899-7071100791634.jpg", affiliate_url: "#", style_tags: ["klassisk"], color_tags: ["gull"], room_tags: ["stue"], dimensions: {width:30,depth:0,height:0}, in_stock: true },
    { name: "Bordduk lin beige", brand: "Kremmerhuset", category: "dekor", price: 249, image_url: "https://kremmerhuset.no/sites/default/files/styles/product_zoom/public/product_images/1734723049-7071100792525.jpg", affiliate_url: "#", style_tags: ["klassisk"], color_tags: ["beige"], room_tags: ["kjøkken"], dimensions: {width:140,depth:140,height:1}, in_stock: true },
    { name: "Telysholder glass", brand: "Kremmerhuset", category: "dekor", price: 59, image_url: "https://kremmerhuset.no/sites/default/files/styles/product_zoom/public/product_images/1734722899-7071100791634.jpg", affiliate_url: "#", style_tags: ["klassisk"], color_tags: ["klar"], room_tags: ["stue"], dimensions: {width:5,depth:5,height:7}, in_stock: true },
    { name: "Luftfuktermist skog", brand: "Kremmerhuset", category: "dekor", price: 179, image_url: "https://kremmerhuset.no/sites/default/files/styles/product_zoom/public/product_images/1734723049-7071100792525.jpg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["hvit"], room_tags: ["stue"], dimensions: {width:10,depth:10,height:15}, in_stock: true },
    { name: "Stor lanterne stål", brand: "Kremmerhuset", category: "dekor", price: 329, image_url: "https://kremmerhuset.no/sites/default/files/styles/product_zoom/public/product_images/1734722899-7071100791634.jpg", affiliate_url: "#", style_tags: ["nordisk"], color_tags: ["svart"], room_tags: ["utendør"], dimensions: {width:25,depth:25,height:35}, in_stock: true },
    // Chilli (14)
    { name: "Chilli sofagruppe grå", brand: "Chilli", category: "sofa", price: 9990, image_url: "https://www.chilli.no/assets/blobs/m%C3%B8bler-sofaer-sovesofaer-sovesofa-eksjo-220-cm-gr%C3%A5/1010733(9)-406dad69e7.jpeg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["grå"], room_tags: ["stue"], dimensions: {width:250,depth:95,height:85}, in_stock: true },
    { name: "TV-benk Chilli", brand: "Chilli", category: "hylle", price: 2490, image_url: "https://www.chilli.no/assets/blobs/oppbevaring-hylle-bokhylle-calvia-hylle-89-cm-hvit/071d397f-ab06-4626-8895-6cb8b8fecf11-a328f61d6f.jpeg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["hvit"], room_tags: ["stue"], dimensions: {width:140,depth:40,height:50}, in_stock: true },
    { name: "Chilli spisebord", brand: "Chilli", category: "bord", price: 3990, image_url: "https://www.chilli.no/assets/blobs/m%C3%B8bler-bord-avlastningsbord-lampebord-sidebord-falan-sidebord-40-cm-sekskant/923eeefd-6ee3-462e-a6c9-64f6bc8e653c-b9344e58cd.jpeg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["tre"], room_tags: ["kjøkken"], dimensions: {width:150,depth:85,height:75}, in_stock: true },
    { name: "Chilli stol sort", brand: "Chilli", category: "stol", price: 799, image_url: "https://www.chilli.no/assets/blobs/m%C3%B8bler-stoler-spisestol-sanroman-classic-brun-m%C3%B8rk-eik-brun-m%C3%B8rk-eik/c6420306-8376-4533-ab48-ab0438569f00-7fa566e330.jpeg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["svart"], room_tags: ["kjøkken"], dimensions: {width:50,depth:52,height:88}, in_stock: true },
    { name: "Chilli hylle hvit", brand: "Chilli", category: "hylle", price: 1290, image_url: "https://www.chilli.no/assets/blobs/oppbevaring-hylle-bokhylle-calvia-hylle-89-cm-hvit/071d397f-ab06-4626-8895-6cb8b8fecf11-a328f61d6f.jpeg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["hvit"], room_tags: ["stue"], dimensions: {width:80,depth:28,height:170}, in_stock: true },
    { name: "Chilli sofabord tre", brand: "Chilli", category: "bord", price: 1490, image_url: "https://www.chilli.no/assets/blobs/m%C3%B8bler-bord-avlastningsbord-lampebord-sidebord-falan-sidebord-40-cm-sekskant/923eeefd-6ee3-462e-a6c9-64f6bc8e653c-b9344e58cd.jpeg", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["tre"], room_tags: ["stue"], dimensions: {width:90,depth:55,height:42}, in_stock: true },
    { name: "Chilli fåtølj", brand: "Chilli", category: "stol", price: 2190, image_url: "https://www.chilli.no/assets/blobs/m%C3%B8bler-stoler-spisestol-sanroman-classic-brun-m%C3%B8rk-eik-brun-m%C3%B8rk-eik/c6420306-8376-4533-ab48-ab0438569f00-7fa566e330.jpeg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["grå"], room_tags: ["stue"], dimensions: {width:68,depth:72,height:90}, in_stock: true },
    { name: "Chilli nattbord", brand: "Chilli", category: "bord", price: 599, image_url: "https://www.chilli.no/assets/blobs/m%C3%B8bler-bord-avlastningsbord-lampebord-sidebord-falan-sidebord-40-cm-sekskant/923eeefd-6ee3-462e-a6c9-64f6bc8e653c-b9344e58cd.jpeg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["hvit"], room_tags: ["soverom"], dimensions: {width:40,depth:35,height:55}, in_stock: true },
    { name: "Chilli spisestol", brand: "Chilli", category: "stol", price: 649, image_url: "https://www.chilli.no/assets/blobs/m%C3%B8bler-stoler-spisestol-sanroman-classic-brun-m%C3%B8rk-eik-brun-m%C3%B8rk-eik/c6420306-8376-4533-ab48-ab0438569f00-7fa566e330.jpeg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["krem"], room_tags: ["kjøkken"], dimensions: {width:48,depth:50,height:85}, in_stock: true },
    { name: "Chilli L-sofa", brand: "Chilli", category: "sofa", price: 11990, image_url: "https://www.chilli.no/assets/blobs/m%C3%B8bler-sofaer-sovesofaer-sovesofa-eksjo-220-cm-gr%C3%A5/1010733(9)-406dad69e7.jpeg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["grå"], room_tags: ["stue"], dimensions: {width:270,depth:100,height:85}, in_stock: true },
    { name: "Chilli bokhylle", brand: "Chilli", category: "hylle", price: 1690, image_url: "https://www.chilli.no/assets/blobs/oppbevaring-hylle-bokhylle-calvia-hylle-89-cm-hvit/071d397f-ab06-4626-8895-6cb8b8fecf11-a328f61d6f.jpeg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["hvit"], room_tags: ["stue", "kontor"], dimensions: {width:75,depth:30,height:180}, in_stock: true },
    // COOP Obs (11)
    { name: "Obs sofagruppe grå", brand: "COOP Obs", category: "sofa", price: 6990, image_url: "https://www.obs.no/cdn-cgi/image/width=640,format=auto/globalassets/productimages/1034376_7029289902402_1.jpg", affiliate_url: "#", style_tags: ["rimelig"], color_tags: ["grå"], room_tags: ["stue"], dimensions: {width:220,depth:90,height:82}, in_stock: true },
    { name: "Obs spisebord", brand: "COOP Obs", category: "bord", price: 2490, image_url: "https://www.obs.no/cdn-cgi/image/width=640,format=auto/globalassets/productimages/893414_5709386739447_1.jpg", affiliate_url: "#", style_tags: ["rimelig"], color_tags: ["tre"], room_tags: ["kjøkken"], dimensions: {width:130,depth:80,height:75}, in_stock: true },
    { name: "Obs hylle", brand: "COOP Obs", category: "hylle", price: 699, image_url: "https://www.obs.no/cdn-cgi/image/width=640,format=auto/globalassets/productimages/721668_5709386726126_1.jpg", affiliate_url: "#", style_tags: ["rimelig"], color_tags: ["hvit"], room_tags: ["stue"], dimensions: {width:60,depth:25,height:130}, in_stock: true },
    { name: "Obs sofabord", brand: "COOP Obs", category: "bord", price: 599, image_url: "https://www.obs.no/cdn-cgi/image/width=640,format=auto/globalassets/productimages/976697_5709386726362_1.jpg", affiliate_url: "#", style_tags: ["rimelig"], color_tags: ["tre"], room_tags: ["stue"], dimensions: {width:80,depth:50,height:40}, in_stock: true },
    { name: "Obs nattbord", brand: "COOP Obs", category: "bord", price: 399, image_url: "https://www.obs.no/cdn-cgi/image/width=640,format=auto/globalassets/productimages/893414_5709386739447_1.jpg", affiliate_url: "#", style_tags: ["rimelig"], color_tags: ["hvit"], room_tags: ["soverom"], dimensions: {width:35,depth:30,height:50}, in_stock: true },
    // A-Møbler (13)
    { name: "A-Møbler hjørnesofa", brand: "A-Møbler", category: "sofa", price: 11990, image_url: "https://www.a-mobler.no/storage/22EA2A330E654E3E239165FBA4FA02914AFDDBDC5F988A1C78B96F720EBF6F73/72ad7bcbcae8420db5e33be2f30bae2f/300-212-0-png.Png/media/35b61a2c2b604f83940a657e539d9721/RB1570010103_H.png", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["grå"], room_tags: ["stue"], dimensions: {width:260,depth:95,height:85}, in_stock: true },
    { name: "A-Møbler seng", brand: "A-Møbler", category: "seng", price: 4290, image_url: "https://www.a-mobler.no/storage/8CE5CF538F3192A0532354957C27C90BB5F734348092040373F70CE429CA270E/76c2e1f7939c48a5a41d2d65d47eeac3/420-298-0-png.Png/media/64331602ba3a41b69658e8d0029ac6d8/RT14300108000100_H.png", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["hvit"], room_tags: ["soverom"], dimensions: {width:160,depth:210,height:95}, in_stock: true },
    { name: "A-Møbler spisebord", brand: "A-Møbler", category: "bord", price: 4590, image_url: "https://www.a-mobler.no/storage/2DC71DCAB15B91AC27FC42E201F99DB19AA989548C0DADD2B840661FC46D311E/c9d7d607b6da4bb69970e59ede98e653/420-298-0-png.Png/media/8f493088002046a385da628e12d26b65/SE1810352106_H.png", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["tre"], room_tags: ["kjøkken"], dimensions: {width:160,depth:85,height:75}, in_stock: true },
    { name: "A-Møbler stol", brand: "A-Møbler", category: "stol", price: 1090, image_url: "https://www.a-mobler.no/storage/4C4A1E26D132C3D04BAA44D3ACE0846481503FEAB6DF22FCD9239488DCE5B756/694bf678518a4bc7aab196052b2171df/420-298-0-png.Png/media/62c69c60782c429899a29ff94c60df64/MR1730022292_H.png", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["grå"], room_tags: ["kjøkken"], dimensions: {width:52,depth:54,height:88}, in_stock: true },
    { name: "A-Møbler kommode", brand: "A-Møbler", category: "kommode", price: 1890, image_url: "https://www.a-mobler.no/storage/11202BD7ED836F2297B07A544094499911E470FF1B8A834E6F1CE27DC0195BC2/627458aff64345d48476d4d9649e34b4/420-298-0-png.Png/media/a2c8f00042634df78958ada4a0134841/FR1920010414.png", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["hvit"], room_tags: ["soverom"], dimensions: {width:70,depth:42,height:90}, in_stock: true },
    { name: "A-Møbler sofabord", brand: "A-Møbler", category: "bord", price: 1390, image_url: "https://www.a-mobler.no/storage/2B34D485425470303468DB91CD1718E0C43B3E5F98323DC20A45DE9619DFFC70/d1924f02fec34a458dc9f021e0a6c3c8/420-298-0-png.Png/media/5c679ad8e0f24ed7bc15bdaeb75701fd/SE18501_H.png", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["tre"], room_tags: ["stue"], dimensions: {width:100,depth:60,height:45}, in_stock: true },
    { name: "A-Møbler divan", brand: "A-Møbler", category: "seng", price: 2890, image_url: "https://www.a-mobler.no/storage/8CE5CF538F3192A0532354957C27C90BB5F734348092040373F70CE429CA270E/76c2e1f7939c48a5a41d2d65d47eeac3/420-298-0-png.Png/media/64331602ba3a41b69658e8d0029ac6d8/RT14300108000100_H.png", affiliate_url: "#", style_tags: ["komfortabel"], color_tags: ["beige"], room_tags: ["soverom"], dimensions: {width:160,depth:210,height:80}, in_stock: true },
    { name: "A-Møbler fåtølj", brand: "A-Møbler", category: "stol", price: 2490, image_url: "https://www.a-mobler.no/storage/F0DB65ADDE3D7E43DF0C36813322E88756B3CA0D532BA3BCD1EE0808855544F5/e044a8df1ed946ae9258ff5f22f9fece/300-212-0-png.Png/media/f04d0ef17a0046eeb5ac045fd9ee41c2/UQ1820050525.png", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["grå"], room_tags: ["stue"], dimensions: {width:70,depth:75,height:95}, in_stock: true },
    { name: "A-Møbler sengeramme", brand: "A-Møbler", category: "seng", price: 3490, image_url: "https://www.a-mobler.no/storage/8CE5CF538F3192A0532354957C27C90BB5F734348092040373F70CE429CA270E/76c2e1f7939c48a5a41d2d65d47eeac3/420-298-0-png.Png/media/64331602ba3a41b69658e8d0029ac6d8/RT14300108000100_H.png", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["hvit"], room_tags: ["soverom"], dimensions: {width:160,depth:210,height:100}, in_stock: true },
    { name: "A-Møbler nattbord", brand: "A-Møbler", category: "bord", price: 699, image_url: "https://www.a-mobler.no/storage/2DC71DCAB15B91AC27FC42E201F99DB19AA989548C0DADD2B840661FC46D311E/c9d7d607b6da4bb69970e59ede98e653/420-298-0-png.Png/media/8f493088002046a385da628e12d26b65/SE1810352106_H.png", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["hvit"], room_tags: ["soverom"], dimensions: {width:42,depth:35,height:55}, in_stock: true },
    { name: "A-Møbler spisestol", brand: "A-Møbler", category: "stol", price: 599, image_url: "https://www.a-mobler.no/storage/86172DA5873510DAA77E8E7A40536CBBB466F4239B2B7A58549569CBD70EAED3/a05c1e40e6a7408183e483362c781736/300-212-0-png.Png/media/589d7c2d715e4866b3d9ea62baa4bb13/MR18202008048.png", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["beige"], room_tags: ["kjøkken"], dimensions: {width:48,depth:50,height:85}, in_stock: true },
    // -- Runde 3 utvidelse (159) --
    // IKEA
    { name: "SINNERLIG bordlampe", brand: "IKEA", category: "lampe", price: 699, image_url: "https://www.ikea.com/no/no/images/products/sinnerlig-gulvlampe-bambus-handlaget__1102331_pe866913_s5.jpg", affiliate_url: "#", style_tags: ["naturlig"], color_tags: ["bambus"], room_tags: ["stue", "soverom"], dimensions: {width:22,depth:22,height:54}, in_stock: true },
    { name: "HEMNES kommode 8 skuffer", brand: "IKEA", category: "kommode", price: 2495, image_url: "https://www.ikea.com/no/no/images/products/hemnes-seng-hvit-beis__0637516_pe698353_s5.jpg", affiliate_url: "#", style_tags: ["tradisjonell"], color_tags: ["hvit"], room_tags: ["soverom"], dimensions: {width:160,depth:50,height:96}, in_stock: true },
    { name: "BESTA vitrine", brand: "IKEA", category: "hylle", price: 3495, image_url: "https://www.ikea.com/no/no/images/products/besta-tv-benk-hvit__0384984_pe557581_s5.jpg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["hvit", "tre"], room_tags: ["stue"], dimensions: {width:120,depth:42,height:128}, in_stock: true },
    // Bohus
    // Bolia
    { name: "Cosima modulsofa", brand: "Bolia", category: "sofa", price: 24990, image_url: "https://images.bolia.com/cdn-cgi/image/width=1100,height=530,fit=pad/products/01-026-20_8112329.webp?cachebusting=2", affiliate_url: "#", style_tags: ["moderne", "premium"], color_tags: ["gra"], room_tags: ["stue"], dimensions: {width:280,depth:100,height:78}, in_stock: true },
    { name: "Floema salongbord", brand: "Bolia", category: "bord", price: 3990, image_url: "https://images.bolia.com/cdn-cgi/image/width=1100,height=530,fit=pad/products/03-033-70_6816336.webp?cachebusting=2", affiliate_url: "#", style_tags: ["minimalistisk"], color_tags: ["tre", "svart"], room_tags: ["stue"], dimensions: {width:90,depth:90,height:38}, in_stock: true },
    { name: "Seed spisestol", brand: "Bolia", category: "stol", price: 2490, image_url: "https://images.bolia.com/cdn-cgi/image/width=1100,height=530,fit=pad/products/02-103-10_00002.webp?cachebusting=0", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["gra", "tre"], room_tags: ["spisestue"], dimensions: {width:50,depth:54,height:82}, in_stock: true },
    { name: "Vitoria gardin lin", brand: "Bolia", category: "gardin", price: 899, image_url: "https://images.bolia.com/cdn-cgi/image/width=1100,height=530,fit=pad/products/21-230-02_00003.webp?cachebusting=2", affiliate_url: "#", style_tags: ["minimalistisk"], color_tags: ["beige"], room_tags: ["stue"], dimensions: {width:140,depth:0,height:260}, in_stock: true },
    { name: "Drum gulvlampe", brand: "Bolia", category: "lampe", price: 3990, image_url: "https://images.bolia.com/cdn-cgi/image/width=1100,height=530,fit=pad/products/20-129-01_00001.webp?cachebusting=2", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["hvit", "messing"], room_tags: ["stue"], dimensions: {width:40,depth:40,height:150}, in_stock: true },
    { name: "Grace seng", brand: "Bolia", category: "seng", price: 14990, image_url: "https://images.bolia.com/cdn-cgi/image/width=1100,height=530,fit=pad/products/01-500-10_00002.webp?cachebusting=4", affiliate_url: "#", style_tags: ["moderne", "premium"], color_tags: ["gra", "tre"], room_tags: ["soverom"], dimensions: {width:180,depth:215,height:95}, in_stock: true },
    { name: "Kite kommode", brand: "Bolia", category: "kommode", price: 7990, image_url: "https://images.bolia.com/cdn-cgi/image/width=1100,height=530,fit=pad/products/04-007-38_4802.webp?cachebusting=0", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["tre", "hvit"], room_tags: ["soverom"], dimensions: {width:120,depth:48,height:80}, in_stock: true },
    // Jysk
    { name: "GEDSER sofa 3-seter", brand: "Jysk", category: "sofa", price: 3999, image_url: "https://s3.eu-west-2.amazonaws.com/imagerepositorypressloft/clients/36565/m/8367838_m.jpg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["gra"], room_tags: ["stue"], dimensions: {width:195,depth:85,height:80}, in_stock: true },
    { name: "AULUM seng 160", brand: "Jysk", category: "seng", price: 2499, image_url: "https://s3.eu-west-2.amazonaws.com/imagerepositorypressloft/clients/36565/m/7260587_m.jpg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["hvit"], room_tags: ["soverom"], dimensions: {width:160,depth:210,height:88}, in_stock: true },
    { name: "KALUNDBORG nattbord", brand: "Jysk", category: "bord", price: 499, image_url: "https://s3.eu-west-2.amazonaws.com/imagerepositorypressloft/clients/36565/m/7260603_m.jpg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["hvit"], room_tags: ["soverom"], dimensions: {width:40,depth:35,height:50}, in_stock: true },
    { name: "NORAGER stol", brand: "Jysk", category: "stol", price: 799, image_url: "https://s3.eu-west-2.amazonaws.com/imagerepositorypressloft/clients/36565/m/7316647_m.jpg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["svart"], room_tags: ["kjokken"], dimensions: {width:48,depth:52,height:85}, in_stock: true },
    { name: "RINGSTED kommode 6 skuffer", brand: "Jysk", category: "kommode", price: 1999, image_url: "https://s3.eu-west-2.amazonaws.com/imagerepositorypressloft/clients/36565/m/7260601_m.jpg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["hvit", "tre"], room_tags: ["soverom"], dimensions: {width:80,depth:42,height:95}, in_stock: true },
    { name: "HJERTING gulvlampe", brand: "Jysk", category: "lampe", price: 599, image_url: "https://s3.eu-west-2.amazonaws.com/imagerepositorypressloft/clients/36565/m/7618068_m.jpg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["svart"], room_tags: ["stue"], dimensions: {width:28,depth:28,height:150}, in_stock: true },
    { name: "BOGENSE dekor bilderamme sett", brand: "Jysk", category: "dekor", price: 199, image_url: "https://s3.eu-west-2.amazonaws.com/imagerepositorypressloft/clients/36565/m/7608142_m.jpg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["svart"], room_tags: ["stue", "gang"], dimensions: {width:40,depth:2,height:50}, in_stock: true },
    // Kid
    { name: "Tromso gardin hvit", brand: "Kid", category: "gardin", price: 399, image_url: "https://www.kid.no/globalassets/productimages/206126220070.jpg?ref=6CD6ADC981&w=590&h=787&mode=pad", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["hvit"], room_tags: ["stue", "soverom"], dimensions: {width:140,depth:0,height:250}, in_stock: true },
    { name: "Bodo dekorlykt", brand: "Kid", category: "dekor", price: 199, image_url: "https://www.kid.no/globalassets/productimages/262001299.jpg?ref=86A80AC43D&w=590&h=787&mode=pad", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["svart"], room_tags: ["stue"], dimensions: {width:15,depth:15,height:25}, in_stock: true },
    // Skeidar
    { name: "Drammen hjornesofa", brand: "Skeidar", category: "sofa", price: 15990, image_url: "https://www.skeidar.no/globalassets/9999/alle-produkter/alle-sofaer/sofa/112295_sjv2oehneve16sorteben_100_001.jpg?id=q9oWq+", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["gra"], room_tags: ["stue"], dimensions: {width:260,depth:100,height:85}, in_stock: true },
    { name: "Fredrikstad spisebord eik", brand: "Skeidar", category: "bord", price: 6990, image_url: "https://www.skeidar.no/globalassets/9999/alle-produkter/alle-bord/spisebord/108880_210cm_hvitoljet_100_001.jpg?id=6e+C9n", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["tre"], room_tags: ["spisestue"], dimensions: {width:180,depth:90,height:75}, in_stock: true },
    { name: "Lillestrom stol polstret", brand: "Skeidar", category: "stol", price: 1490, image_url: "https://www.skeidar.no/globalassets/9999/alle-produkter/alle-stoler/spisestoler/115523_ubehandleteikmedseteisydneysvart_000_001.jpg?id=vnveF2", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["gra"], room_tags: ["spisestue"], dimensions: {width:52,depth:56,height:88}, in_stock: true },
    { name: "Kongsberg seng 180", brand: "Skeidar", category: "seng", price: 9990, image_url: "https://www.skeidar.no/globalassets/9999/alle-produkter/alle-senger-og-madrasser/kontinentalsenger/110798_200x210cmtekstildreamgreyintegrertovermadras_000_001.jpg?id=EdAyWW", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["tre", "hvit"], room_tags: ["soverom"], dimensions: {width:180,depth:210,height:100}, in_stock: true },
    { name: "Gjovik kommode eik", brand: "Skeidar", category: "kommode", price: 4490, image_url: "https://www.skeidar.no/globalassets/9999/alle-produkter/all-oppbevaring-og-skap/kommoder/111878_3_sort_000_001.jpg?id=6I6N7q", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["tre"], room_tags: ["soverom"], dimensions: {width:110,depth:45,height:85}, in_stock: true },
    { name: "Moss gulvlampe", brand: "Skeidar", category: "lampe", price: 1890, image_url: "https://www.skeidar.no/globalassets/9999/alle-produkter/all-belysning/gulvlamper/113478_rosa_000_001.jpg?id=UdhkW+", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["svart", "messing"], room_tags: ["stue"], dimensions: {width:35,depth:35,height:155}, in_stock: true },
    { name: "Sarpsborg pute", brand: "Skeidar", category: "pute", price: 349, image_url: "https://www.skeidar.no/globalassets/9999/alle-produkter/alle-tekstiler-og-sengetoy/pynteputer-og-putetrekk/117938_100_001.jpg?id=JDPSIY", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["beige"], room_tags: ["stue", "soverom"], dimensions: {width:50,depth:50,height:15}, in_stock: true },
    // Norsk Interiør
    // Princess
    { name: "Satin sengetoy gra", brand: "Princess", category: "dekor", price: 499, image_url: "https://princessbutikken.b-cdn.net/images/thumbs/0033218_hailey-pledd-130x170-beige_550.jpeg", affiliate_url: "#", style_tags: ["luksus"], color_tags: ["gra"], room_tags: ["soverom"], dimensions: {width:200,depth:0,height:0}, in_stock: true },
    { name: "Fleece pledd hvit", brand: "Princess", category: "dekor", price: 299, image_url: "https://princessbutikken.b-cdn.net/images/thumbs/0039411_andrina-lysestake-19-cm_550.jpeg", affiliate_url: "#", style_tags: ["komfortabel"], color_tags: ["hvit"], room_tags: ["stue", "soverom"], dimensions: {width:150,depth:200,height:1}, in_stock: true },
    // Møbelringen
    { name: "Haugesund sofa 2-seter", brand: "Møbelringen", category: "sofa", price: 7990, image_url: "https://backend.mobelringen.no/media/catalog/product/3/2/322319001_8639326.png?width=650&height=650&quality=80&fit=bounds&optimise=high", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["beige"], room_tags: ["stue"], dimensions: {width:180,depth:90,height:82}, in_stock: true },
    { name: "Larvik kommode stor", brand: "Møbelringen", category: "kommode", price: 4290, image_url: "https://backend.mobelringen.no/media/catalog/product/5/7/5755383_oslo_kommode_4_skf_copy.png?width=650&height=650&quality=80&fit=bounds&optimise=high", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["hvit", "tre"], room_tags: ["soverom"], dimensions: {width:120,depth:45,height:82}, in_stock: true },
    { name: "Halden lampe messing", brand: "Møbelringen", category: "lampe", price: 1290, image_url: "https://backend.mobelringen.no/media/catalog/product/3/1/317325_9099348.png?width=650&height=650&quality=80&fit=bounds&optimise=high", affiliate_url: "#", style_tags: ["klassisk"], color_tags: ["messing"], room_tags: ["stue"], dimensions: {width:30,depth:30,height:48}, in_stock: true },
    // Fagmøbler
    { name: "Klassisk hylle eik", brand: "Fagmøbler", category: "hylle", price: 4490, image_url: "https://imagedelivery.net/LfHarEEHw85fo7v7-lUDxQ/62daa4e8-6f9f-49c0-d573-503298217b00/public", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["tre"], room_tags: ["stue", "kontor"], dimensions: {width:90,depth:35,height:190}, in_stock: true },
    // Home & Cottage
    // Elkjøp
    { name: "Philips Hue Go bordlampe", brand: "Elkjøp", category: "lampe", price: 699, image_url: "https://next-media.elkjop.com/image/dv_web_D180001280327476/283375/led-mane-lampe-18-cm.jpg?w=640&q=75", affiliate_url: "#", style_tags: ["smart"], color_tags: ["hvit"], room_tags: ["soverom", "stue"], dimensions: {width:15,depth:15,height:8}, in_stock: true },
    { name: "Ikea SYMFONISK lampe", brand: "Elkjøp", category: "lampe", price: 1499, image_url: "https://next-media.elkjop.com/image/dv_web_D18000130317980/883921/moderne-bordlampe-med-beroringsfunksjon-fra-articasa-metall-svart.jpg", affiliate_url: "#", style_tags: ["smart", "skandinavisk"], color_tags: ["hvit"], room_tags: ["stue", "soverom"], dimensions: {width:15,depth:15,height:35}, in_stock: true },
    { name: "LED taklampe smart", brand: "Elkjøp", category: "lampe", price: 899, image_url: "https://next-media.elkjop.com/image/dv_web_D180001005124200/60589/krystall-lampe-magisk-glasskule.jpg?w=640&q=75", affiliate_url: "#", style_tags: ["smart", "moderne"], color_tags: ["hvit"], room_tags: ["stue", "soverom"], dimensions: {width:40,depth:40,height:8}, in_stock: true },
    // Kremmerhuset
    { name: "Duftlys Rosmarin", brand: "Kremmerhuset", category: "dekor", price: 89, image_url: "https://kremmerhuset.no/sites/default/files/styles/product_zoom/public/product_images/1734723049-7071100792525.jpg", affiliate_url: "#", style_tags: ["koselig"], color_tags: ["gronn"], room_tags: ["stue"], dimensions: {width:8,depth:8,height:10}, in_stock: true },
    { name: "Keramikk vase stor", brand: "Kremmerhuset", category: "dekor", price: 349, image_url: "https://kremmerhuset.no/sites/default/files/styles/product_zoom/public/product_images/1734722899-7071100791634.jpg", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["hvit"], room_tags: ["stue"], dimensions: {width:18,depth:18,height:35}, in_stock: true },
    { name: "Pledd alpakka stor", brand: "Kremmerhuset", category: "dekor", price: 899, image_url: "https://kremmerhuset.no/sites/default/files/styles/product_zoom/public/product_images/1734723049-7071100792525.jpg", affiliate_url: "#", style_tags: ["luksus"], color_tags: ["gra", "beige"], room_tags: ["stue"], dimensions: {width:140,depth:200,height:1}, in_stock: true },
    { name: "Lyslenke inne 3m", brand: "Kremmerhuset", category: "lampe", price: 199, image_url: "https://kremmerhuset.no/sites/default/files/product_images/1671557249-7071100774668.jpg", affiliate_url: "#", style_tags: ["dekorativ"], color_tags: ["varm hvit"], room_tags: ["stue", "soverom"], dimensions: {width:300,depth:1,height:1}, in_stock: true },
    { name: "Serveringsfat tre", brand: "Kremmerhuset", category: "dekor", price: 179, image_url: "https://kremmerhuset.no/sites/default/files/styles/product_zoom/public/product_images/1734722899-7071100791634.jpg", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["tre"], room_tags: ["kjokken"], dimensions: {width:40,depth:25,height:3}, in_stock: true },
    { name: "Blomstervase glass", brand: "Kremmerhuset", category: "dekor", price: 149, image_url: "https://kremmerhuset.no/sites/default/files/styles/product_zoom/public/product_images/1734723049-7071100792525.jpg", affiliate_url: "#", style_tags: ["minimalistisk"], color_tags: ["klar"], room_tags: ["stue"], dimensions: {width:12,depth:12,height:25}, in_stock: true },
    // Chilli
    { name: "Chilli L-sofa beige", brand: "Chilli", category: "sofa", price: 12990, image_url: "https://www.chilli.no/assets/blobs/m%C3%B8bler-sofaer-sovesofaer-sovesofa-eksjo-220-cm-gr%C3%A5/1010733(9)-406dad69e7.jpeg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["beige"], room_tags: ["stue"], dimensions: {width:260,depth:95,height:82}, in_stock: true },
    { name: "Chilli gulvlampe", brand: "Chilli", category: "lampe", price: 799, image_url: "https://www.chilli.no/assets/blobs/belysning-innend%C3%B8rsbelysning-lamper-gulvlampe-crestor-flerfarget-narwanike-farger-flerfarget-narwanike-farger/c75d2747-b487-436c-b052-311dead38529-ffd4ec5e53.jpeg", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["svart"], room_tags: ["stue"], dimensions: {width:28,depth:28,height:155}, in_stock: true },
    // COOP Obs
    { name: "Obs dekorvase", brand: "COOP Obs", category: "dekor", price: 129, image_url: "https://www.obs.no/cdn-cgi/image/width=640,format=auto/globalassets/productimages/721423_7071189295948_1.jpg", affiliate_url: "#", style_tags: ["rimelig"], color_tags: ["hvit"], room_tags: ["stue"], dimensions: {width:12,depth:12,height:22}, in_stock: true },
    { name: "Obs pledd fleece", brand: "COOP Obs", category: "dekor", price: 199, image_url: "https://www.obs.no/cdn-cgi/image/width=640,format=auto/globalassets/productimages/721423_7071189295948_1.jpg", affiliate_url: "#", style_tags: ["rimelig"], color_tags: ["gra"], room_tags: ["stue", "soverom"], dimensions: {width:130,depth:170,height:1}, in_stock: true },
    { name: "Obs bokhylle", brand: "COOP Obs", category: "hylle", price: 999, image_url: "https://www.obs.no/cdn-cgi/image/width=640,format=auto/globalassets/productimages/1104287_5714988035798_1.jpg", affiliate_url: "#", style_tags: ["rimelig"], color_tags: ["hvit", "tre"], room_tags: ["stue", "kontor"], dimensions: {width:80,depth:28,height:180}, in_stock: true },
    { name: "Obs TV-benk", brand: "COOP Obs", category: "hylle", price: 899, image_url: "https://www.obs.no/cdn-cgi/image/width=640,format=auto/globalassets/productimages/721668_5709386726126_1.jpg", affiliate_url: "#", style_tags: ["rimelig"], color_tags: ["hvit"], room_tags: ["stue"], dimensions: {width:120,depth:38,height:48}, in_stock: true },
    // A-Møbler
    { name: "A-Møbler teppe 200x300", brand: "A-Møbler", category: "teppe", price: 2490, image_url: "https://www.a-mobler.no/storage/49837245767106C484468D44313746DFF0736D60C863FE8D91F2A4E99EF3BB72/4d19001ffb9d48229703721379d80deb/300-212-0-png.Png/media/289e4a87af5a47afbb4a5eb9ab47ced2/GX94115203313.png", affiliate_url: "#", style_tags: ["skandinavisk"], color_tags: ["gra", "beige"], room_tags: ["stue"], dimensions: {width:200,depth:300,height:2}, in_stock: true },
    { name: "A-Møbler spisestol polstret", brand: "A-Møbler", category: "stol", price: 899, image_url: "https://www.a-mobler.no/storage/4C4A1E26D132C3D04BAA44D3ACE0846481503FEAB6DF22FCD9239488DCE5B756/694bf678518a4bc7aab196052b2171df/420-298-0-png.Png/media/62c69c60782c429899a29ff94c60df64/MR1730022292_H.png", affiliate_url: "#", style_tags: ["moderne"], color_tags: ["gra"], room_tags: ["kjokken"], dimensions: {width:50,depth:52,height:85}, in_stock: true },
    // Skogstad
    // HAY
    { name: "HAY Mags sofa", brand: "HAY", category: "sofa", price: 19990, image_url: "https://www.hay.com/globalassets/inriver/integration/service/mags-25-seater-combination-1_brandmodel.jpg", affiliate_url: "#", style_tags: ["minimalistisk", "design"], color_tags: ["gra"], room_tags: ["stue"], dimensions: {width:228,depth:95,height:67}, in_stock: true },
    { name: "HAY AAC22 stol", brand: "HAY", category: "stol", price: 2790, image_url: "https://www.hay.com/img_20250424011708/globalassets/inriver/integration/service/aac-22_910x1100_brandmodel2.jpg", affiliate_url: "#", style_tags: ["minimalistisk", "design"], color_tags: ["svart", "tre"], room_tags: ["spisestue", "kontor"], dimensions: {width:52,depth:50,height:79}, in_stock: true },
    { name: "HAY Mags Soft sofa", brand: "HAY", category: "sofa", price: 22990, image_url: "https://www.hay.com/globalassets/inriver/integration/service/mags-25-seater-combination-1_brandmodel.jpg", affiliate_url: "#", style_tags: ["minimalistisk", "premium"], color_tags: ["beige"], room_tags: ["stue"], dimensions: {width:252,depth:103,height:67}, in_stock: true },
    { name: "HAY About A Chair AAC12", brand: "HAY", category: "stol", price: 1990, image_url: "https://www.hay.com/img_20250424011708/globalassets/inriver/integration/service/aac-22_910x1100_brandmodel2.jpg", affiliate_url: "#", style_tags: ["minimalistisk", "design"], color_tags: ["hvit", "tre"], room_tags: ["spisestue"], dimensions: {width:51,depth:50,height:78}, in_stock: true },
    // Verdens Beste
    // -- Nye merker runde 3b (130) --
    // HTH
    // Flügger
    // Fargerike
    // Clas Ohlson
    // Plantasjen
    // Tilbords
    // Høie
    // Ekornes
    { name: "Stressless Mary sofa 3-seter", brand: "Ekornes", category: "sofa", price: 49990, image_url: "https://www.stressless.com/global/-/media/stresslesssite/products/sofas/anna/annapalomamushroom960x960.jpg", affiliate_url: "#", style_tags: ["klassisk", "premium"], color_tags: ["gra"], room_tags: ["stue"], dimensions: {width:225,depth:90,height:98}, in_stock: true },
    { name: "Stressless Oslo sofa 2-seter", brand: "Ekornes", category: "sofa", price: 34990, image_url: "https://www.stressless.com/en/-/media/stresslesssite/products/sofas/emily960x960.jpg", affiliate_url: "#", style_tags: ["skandinavisk", "premium"], color_tags: ["beige"], room_tags: ["stue"], dimensions: {width:180,depth:85,height:95}, in_stock: true },
    { name: "Stressless Manhattan sofa", brand: "Ekornes", category: "sofa", price: 39990, image_url: "https://www.stressless.com/en/-/media/stresslesssite/products/sofas/stellapalomanewcaramelmodels940x835.jpg", affiliate_url: "#", style_tags: ["moderne", "premium"], color_tags: ["gra"], room_tags: ["stue"], dimensions: {width:210,depth:90,height:88}, in_stock: true },
    { name: "Stressless Windsor sofa", brand: "Ekornes", category: "sofa", price: 44990, image_url: "https://www.stressless.com/global/-/media/stresslesssite/products/sofas/anna/annapalomamushroom960x960.jpg", affiliate_url: "#", style_tags: ["klassisk", "premium"], color_tags: ["brun"], room_tags: ["stue"], dimensions: {width:240,depth:92,height:95}, in_stock: true },
    { name: "Stressless E200 sofa", brand: "Ekornes", category: "sofa", price: 32990, image_url: "https://www.stressless.com/en/-/media/stresslesssite/products/sofas/emily960x960.jpg", affiliate_url: "#", style_tags: ["moderne", "premium"], color_tags: ["hvit"], room_tags: ["stue"], dimensions: {width:195,depth:88,height:82}, in_stock: true },
    // Hødnebø
    { name: "Hødnebø Solli sofa 3-seter", brand: "Hødnebø", category: "sofa", price: 29990, image_url: "https://hodnebo.no/wp-content/uploads/2019/08/Lillesand-15-seter-med-arm-venstre-og-pall-laguna-forest-2-copy-1.jpg", affiliate_url: "#", style_tags: ["skandinavisk", "premium"], color_tags: ["gra"], room_tags: ["stue"], dimensions: {width:230,depth:95,height:80}, in_stock: true },
    { name: "Hødnebø Stovner stol", brand: "Hødnebø", category: "stol", price: 4990, image_url: "https://hodnebo.no/wp-content/uploads/2017/01/langøy-spisestol.jpg", affiliate_url: "#", style_tags: ["skandinavisk", "premium"], color_tags: ["gra", "tre"], room_tags: ["spisestue"], dimensions: {width:52,depth:55,height:82}, in_stock: true },
    { name: "Hødnebø Toyen lenestol", brand: "Hødnebø", category: "stol", price: 8990, image_url: "https://hodnebo.no/wp-content/uploads/2017/01/langøy-spisestol.jpg", affiliate_url: "#", style_tags: ["skandinavisk", "premium"], color_tags: ["gronn", "tre"], room_tags: ["stue"], dimensions: {width:75,depth:80,height:92}, in_stock: true },
    // Slettvoll
    { name: "Slettvoll Grand sofa 3-seter", brand: "Slettvoll", category: "sofa", price: 39990, image_url: "https://d1q8z1f8ga01g7.cloudfront.net/3humagpm6p?changed=2024-12-16", affiliate_url: "#", style_tags: ["skandinavisk", "premium"], color_tags: ["gra"], room_tags: ["stue"], dimensions: {width:240,depth:100,height:82}, in_stock: true },
    { name: "Slettvoll Arc gulvlampe", brand: "Slettvoll", category: "lampe", price: 5990, image_url: "https://d1q8z1f8ga01g7.cloudfront.net/873a2b5dhl?changed=2026-02-04", affiliate_url: "#", style_tags: ["skandinavisk", "premium"], color_tags: ["messing", "svart"], room_tags: ["stue"], dimensions: {width:40,depth:40,height:170}, in_stock: true },
];

async function seed() {
  console.log(`Seeding ${products.length} products...`);

  const { data, error } = await supabase
    .from("products")
    .insert(products)
    .select("id, name");

  if (error) {
    console.error("Seed failed:", error.message);
  } else {
    console.log(`Seeded ${data.length} products successfully!`);
  }
}

seed();
